apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  googleCloudBuild:
    projectId: k8s-skaffold
deploy:
  kubectl:
    manifests:
    - k8s-*
