apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-gcb
    workspace: .
  googleCloudBuild:
    projectId: k8s-skaffold
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s-*
      parameters:
        IMAGE_NAME: gcr.io/k8s-skaffold/skaffold-gcb
