language: go
os:
  - linux
  - osx
go:
  - "1.10.x"
go_import_path: github.com/GoogleContainerTools/skaffold

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - make out/skaffold test
