[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/moby/moby"
  revision = "e1f98e8ab3cb5ae5c0f452cdd81ac4a954279e62"

[[override]]
  name = "github.com/docker/docker"
  revision = "e1f98e8ab3cb5ae5c0f452cdd81ac4a954279e62"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/rjeczalik/notify"
