apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold
    dockerfilePath: deploy/skaffold/Dockerfile
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - deploy/skaffold/*
