apiVersion: skaffold/v1alpha4
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
