apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy: sha256
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold
    workspace: examples/getting-started
  googleCloudBuild:
    projectId: k8s-skaffold
deploy:
  kubectl:
    manifests:
    - paths:
      - examples/getting-started/k8s-*
      parameters:
        IMAGE_NAME: gcr.io/k8s-skaffold/skaffold
